Repository w3c/did, pull requests merged in 2020-07, with the labels that each got.

#331 Support resolve() and resolveStream() functions
  index.html
Labels: contract

#267 Put key points up front
  index.html
Labels: do not merge

#335 full editing pass on all terms
  terms.html
Labels: editorial

#347 Add Metadata section based on infra data structures.
  index.html
Labels: metadata
