Repository w3c/did, pull requests merged in 2021-03, with the labels that each got.

#633 Various cleanups.
  index.html
Labels: editorial

#701 Fix collisions in IANA Media Type file extensions.
  index.html
Labels: non-substantive

#702 Add language about specifying DID URL path semantics.
  index.html
Labels: editorial

#703 Add support for percent-encoded characters for did:web.
  index.html
Labels: substantive

#704 Create acknowledgements section.
  index.html
Labels: editorial

#596 Add diagram "production and consumption".
  diagrams/diagram-production-consumption.png
  index.html
Labels: editorial

#705 Align conformance statements.
  index.html
Labels: editorial

#706 editorial: fix typo in services
  index.html
Labels: editorial

#709 Handling a respec/specref error
  common.js
Labels: editorial
