Repository w3c/did, pull requests merged in 2021-06, with the labels that each got.

#756 Remove at risk note for equivalentId and canonicalId
  index.html
Labels: cr-comment, editorial

#757 Prepare Candidate Recommendation 2 specification.
  CR/2021-06-15/diagrams/diagram-did-document-entries.png
  CR/2021-06-15/diagrams/diagram-did-document-entries.svg
  CR/2021-06-15/diagrams/diagram-production-consumption.png
  CR/2021-06-15/diagrams/diagram-resolve-resolverepresentation.png
  CR/2021-06-15/diagrams/did_brief_architecture_overview.svg
  CR/2021-06-15/diagrams/did_detailed_architecture_overview.svg
  CR/2021-06-15/diagrams/did_url_dereference_overview.svg
  CR/2021-06-15/diagrams/figure-a.1-did-and-did-document-graph.png
  CR/2021-06-15/diagrams/figure-a.2-also-known-as-graph.png
  CR/2021-06-15/diagrams/figure-b.1-controller-and-subject-equivalence.png
  CR/2021-06-15/diagrams/figure-c.1-independent-did-controllers.png
  CR/2021-06-15/diagrams/figure-c.2-group-did-controllers.png
  CR/2021-06-15/diagrams/parts-of-a-did.svg
  CR/2021-06-15/index.html
  index.html
Labels: cr-comment, cr-comment-resolved-implicit, substantive

#754 add appendix text RE change in controller
  index.html
Labels: cr-comment, editorial

#758 Fix editorial issues with Privacy Considerations intro.
  index.html
Labels: cr-comment, editorial

#760 Editorial fixes to DID Correlation Risks section.
  index.html
Labels: cr-comment, editorial

#761 Editorial fixes to DID Document Correlation Risks section.
  index.html
Labels: cr-comment, cr-comment-resolved-explicit, editorial

#762 Update editorial issues with DID Subject Classification section.
  index.html
Labels: cr-comment, cr-comment-resolved-explicit, editorial

#763 Fix editorial issues in Service Privacy section.
  index.html
Labels: cr-comment, editorial

#741 Update Verification Method Rotation section.
  index.html
Labels: cr-comment, editorial

#755 add appendix text RE did subject change
  index.html
Labels: cr-comment, editorial

#765 Speak to when a DID and DID Document start existing.
  index.html
Labels: cr-comment, editorial

#767 Convert 2 diagrams from PNG to SVG.
  diagrams/diagram-production-consumption.png
  diagrams/diagram-production-consumption.svg
  diagrams/diagram-resolve-resolverepresentation.png
  diagrams/diagram-resolve-resolverepresentation.svg
  index.html
Labels: cr-comment, editorial
