Repository w3c/did, pull requests merged in 2021-02, with the labels that each got.

#588 editorial: issue markers for proving control sections, for #583
  index.html
Labels: editorial

#604 editorial: remove strikethrough from feature at risk issues
  index.html
Labels: editorial

#605 fixing `i.e.,` and `e.g.,` punctuation
  index.html
Labels: editorial

#603 Fix appendices sections
  index.html
Labels: editorial

#606 Reference Canonical CBOR rules, and some other fixes.
  index.html
Labels: substantive

#607 Add Candidate Recommendation variables to spec.
  index.html
Labels: editorial

#608 Editorial clean up of Abstract section.
  index.html
Labels: editorial

#609 Prepare Status of the Document section for Candidate Recommendation.
  index.html
Labels: editorial

#610 Describe `@context` as JSON member in JSON-LD production/consumption.
  index.html
Labels: substantive

#612 Replacing Figure 1 with a new 'Brief Architecture Overview' diagram
  diagrams/did_architecture_overview.svg
  diagrams/did_brief_architecture_overview.png
  diagrams/did_brief_architecture_overview.svg
  index.html
Labels: editorial

#611 Editorial rework of Introduction section.
  index.html
Labels: editorial

#614 Editorial clean up for Design Goals section.
  index.html
Labels: editorial

#615 Fix editorial issues with Architecture Overview section.
  index.html
Labels: editorial

#617 Fix editorial issues with Conformance section.
  index.html
Labels: editorial

#620 Fix editorial and normative issues in DID Syntax section.
  index.html
Labels: non-substantive

#621 Fix editorial and normative issues in DID URL Syntax section.
  index.html
Labels: substantive

#622 Fix editorial/normative issues in Path, Query, and Fragment sections.
  index.html
Labels: non-substantive

#623 Change "personally-identifiable information" to "personal data".
  index.html
Labels: editorial

#616 Service privacy section updated
  index.html
Labels: editorial

#624 Change "DID dereferencing" to "DID URL dereferencing".
  index.html
Labels: editorial

#627 Fix editorial/normative issues in DID Parameters.
  index.html
Labels: substantive

#628 Add DID document example in JSON representation.
  index.html
Labels: editorial

#629 Fix editorial issues in Relative DID URLs section.
  index.html
Labels: editorial

#630 Fix editorial issues in Core Properties section.
  index.html
Labels: editorial

#631 Fix editorial issues in Data Model section.
  index.html
Labels: editorial

#632 Fix editorial issues in Identification section.
  index.html
Labels: non-substantive

#636 Fix editorial issues with Verification Relationship intro section.
  index.html
Labels: editorial

#637 Fix editorial issues with Authentication section.
  index.html
Labels: editorial

#638 Fix minor editorial issues with Assertion section.
  index.html
Labels: editorial

#639 Fix editorial issues with Key Agreement section.
  index.html
Labels: editorial

#640 Fix editorial issues with Capability Invocation section.
  index.html
Labels: editorial

#641 Fix editorial issues with Capability Delegation section.
  index.html
Labels: editorial

#642 Fix non-substantive issues with Service section.
  index.html
Labels: non-substantive

#643 Adding definition of 'conforming DID URL dereferencer'
  index.html
Labels: non-substantive

#649 Remove Current Issues appendix.
  index.html
Labels: editorial

#650 Remove the IANA section for application/did+dag+cbor.
  index.html
Labels: editorial

#652 (editorial) add a missing "a" article
  index.html
Labels: editorial

#651 (editorial) minor punctuation and language fixes
  index.html
Labels: editorial

#655 Editorial change on the introductory para DID URL
  index.html
Labels: editorial

#644 Fix substantive issues related to Representations intro section.
  index.html
Labels: substantive

#653 Fix editorial and substantive issues in JSON Production and Consumption section.
  index.html
Labels: substantive

#654 Fix editorial and substantive issues in JSON-LD section.
  index.html
Labels: substantive

#657 Restore example of 'service' and 'relativeRef' parameters.
  index.html
Labels: editorial

#658 (editorial) restore apparently accidental deletion
  index.html
Labels: editorial

#659 (editorial) language fixes too late for #631
  index.html
Labels: editorial

#660 (editorial) replace some markdown with html tags
  index.html
Labels: editorial

#661 (editorial) capabilityDelegation language (+ line lengths)
  index.html
Labels: editorial

#663 Fix editorial and substantive issues in CBOR section.
  index.html
Labels: substantive

#665 Change note on order to advisement
  index.html
Labels: editorial

#666 Substantive updates to DID Method Requirements section.
  index.html
Labels: substantive

#671 Minor editorial change proposals on section 1
  index.html
Labels: editorial

#673 Editorial review of the terminology section
  terms.html
Labels: editorial

#675 Factoring out the 'OPTIONAL' for the parameter table.
  index.html
Labels: editorial

#676 Changed the DID terminology entry (see issue #672)
  terms.html
Labels: editorial

#677 Added a remark whereby an ordered map is sometimes just referred to as "map".
  index.html
Labels: editorial

#681 Re-created figure 3
  ECHIDNA
  diagrams/diagram-did-document-entries.drawio
  diagrams/diagram-did-document-entries.png
  diagrams/diagram-did-document-entries.svg
  index.html
Labels: editorial

#682 Changed the note on semicolon usage
  index.html
Labels: editorial

#683 Re-writing the intro paragraph of §5.1
  index.html
Labels: editorial

#686 Fix "ordered map" language and ensure testability of all MUST statements.
  index.html
Labels: non-substantive

#678 Implement Data Model / Resolution serialization mechanisms.
  index.html
Labels: substantive

#679 Add representation-specific entry map in Production and Consumption.
  index.html
Labels: substantive

#692 Updated the data model diagram
  diagrams/diagram-did-document-entries.drawio
  diagrams/diagram-did-document-entries.png
  diagrams/diagram-did-document-entries.svg
Labels: editorial

#648 Add a diagram depicts DID URL dereference
  diagrams/did_url_dereference_overview.svg
  index.html
Labels: editorial
