Repository w3c/did, pull requests merged in 2021-05, with the labels that each got.

#731 Replace use of publicKeyBase58 with publicKeyMultibase.
  index.html
Labels: cr-comment, substantive

#735 Migrate CBOR representation to NOTE
  index.html
Labels: cr-comment, cr-comment-resolved-explicit, substantive

#736 Update Security Considerations introduction.
  index.html
Labels: cr-comment, cr-comment-resolved-explicit, editorial

#737 Update Choosing DID Resolvers section.
  index.html
Labels: cr-comment, cr-comment-resolved-explicit, editorial

#738 Update Proving Control and Binding section.
  index.html
Labels: cr-comment, editorial

#739 Update non-repudiation section.
  index.html
Labels: cr-comment, cr-comment-resolved-implicit, editorial

#740 Update Key and Signature Expiration section.
  index.html
Labels: cr-comment, cr-comment-resolved-explicit, editorial

#744 Fix editorial issues in The Role of Human-Friendly Identifiers section.
  index.html
Labels: cr-comment, editorial

#745 Fix editorial issues with Enhanced URNs section.
  index.html
Labels: cr-comment, editorial

#746 Update Immutability section in Security Considerations.
  index.html
Labels: cr-comment, editorial

#747 Update Encrypted Data section in Security Considerations.
  index.html
Labels: cr-comment, editorial

#748 Update DID Document examples
  index.html
Labels: cr-comment, editorial

#742 Update Verification Method Revocation section.
  index.html
Labels: cr-comment, editorial

#743 Fix editorial issues with DID Recovery section.
  index.html
Labels: cr-comment, editorial

#749 Fix editorial issues with equivalence properties.
  index.html
Labels: cr-comment, editorial

#750 Fix editorial issues with content integrity protection.
  index.html
Labels: cr-comment, editorial

#751 Fix editorial issues with persistence section.
  index.html
Labels: cr-comment, cr-comment-resolved-explicit, editorial

#752 Fix editorial issues with Level of Assurance section.
  index.html
Labels: cr-comment, cr-comment-resolved-implicit, editorial
