Repository w3c/did, pull requests merged in 2021-04, with the labels that each got.

#711 Post-CR Changes on ECHIDNA (DO NOT MERGE THIS BEFORE CR PUBLICATION)
  ECHIDNA
Labels: cr-comment, cr-comment-resolved-explicit, editorial

#713 Updated the multibase doc. reference
  common.js
Labels: cr-comment, cr-comment-resolved-explicit, editorial

#714 Minor editorial fix: removing superfluous close bracket
  index.html
Labels: cr-comment, cr-comment-resolved-explicit, editorial

#716 Apply small editorial fixes in the Resolution section.
  index.html
Labels: cr-comment, cr-comment-resolved-explicit, editorial

#720 Clarify that equivalentId and canonicalId are optional.
  index.html
Labels: cr-comment, cr-comment-resolved-explicit, non-substantive

#722 chore: Remove at risk note for nextUpdate and nextVersionId
  index.html
Labels: cr-comment, cr-comment-resolved-explicit, editorial

#725 Change "minimal" -> "simple" in DID Document description.
  index.html
Labels: cr-comment, cr-comment-resolved-implicit, editorial
